[[constraint]]
  name = "github.com/rcrowley/go-metrics"
  revision = "9beb055b7962d16947a14e1cd718098a2431e20e"

[[constraint]]
  name = "github.com/wavefronthq/wavefront-sdk-go"
  version = "0.9.3"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.3.0"
